/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class beast_evolution_likelihood_BeerLikelihoodCoreNative */

#ifndef _Included_beast_evolution_likelihood_BeerLikelihoodCoreNative
#define _Included_beast_evolution_likelihood_BeerLikelihoodCoreNative
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     beast_evolution_likelihood_BeerLikelihoodCoreNative
 * Method:    createCppBEERObject
 * Signature: (I)J
 */
JNIEXPORT jlong JNICALL Java_beast_evolution_likelihood_BeerLikelihoodCoreNative_createCppBEERObject
  (JNIEnv *, jobject, jint);

/*
 * Class:     beast_evolution_likelihood_BeerLikelihoodCoreNative
 * Method:    initializeC
 * Signature: (JIIIZ)V
 */
JNIEXPORT void JNICALL Java_beast_evolution_likelihood_BeerLikelihoodCoreNative_initializeC
  (JNIEnv *, jobject, jlong, jint, jint, jint, jboolean);

/*
 * Class:     beast_evolution_likelihood_BeerLikelihoodCoreNative
 * Method:    finalizeC
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_beast_evolution_likelihood_BeerLikelihoodCoreNative_finalizeC
  (JNIEnv *, jobject, jlong);

/*
 * Class:     beast_evolution_likelihood_BeerLikelihoodCoreNative
 * Method:    createNodePartialsC
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_beast_evolution_likelihood_BeerLikelihoodCoreNative_createNodePartialsC
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     beast_evolution_likelihood_BeerLikelihoodCoreNative
 * Method:    setNodePartialsForUpdateC
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_beast_evolution_likelihood_BeerLikelihoodCoreNative_setNodePartialsForUpdateC
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     beast_evolution_likelihood_BeerLikelihoodCoreNative
 * Method:    setNodeStatesForUpdateC
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_beast_evolution_likelihood_BeerLikelihoodCoreNative_setNodeStatesForUpdateC
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     beast_evolution_likelihood_BeerLikelihoodCoreNative
 * Method:    setNodeStatesC
 * Signature: (JI[I)V
 */
JNIEXPORT void JNICALL Java_beast_evolution_likelihood_BeerLikelihoodCoreNative_setNodeStatesC
  (JNIEnv *, jobject, jlong, jint, jintArray);

/*
 * Class:     beast_evolution_likelihood_BeerLikelihoodCoreNative
 * Method:    setNodeMatrixForUpdateC
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_beast_evolution_likelihood_BeerLikelihoodCoreNative_setNodeMatrixForUpdateC
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     beast_evolution_likelihood_BeerLikelihoodCoreNative
 * Method:    setNodeMatrixC
 * Signature: (JII[D)V
 */
JNIEXPORT void JNICALL Java_beast_evolution_likelihood_BeerLikelihoodCoreNative_setNodeMatrixC
  (JNIEnv *, jobject, jlong, jint, jint, jdoubleArray);

/*
 * Class:     beast_evolution_likelihood_BeerLikelihoodCoreNative
 * Method:    setPaddedMatricesC
 * Signature: (JI[D)V
 */
JNIEXPORT void JNICALL Java_beast_evolution_likelihood_BeerLikelihoodCoreNative_setPaddedMatricesC
  (JNIEnv *, jobject, jlong, jint, jdoubleArray);

/*
 * Class:     beast_evolution_likelihood_BeerLikelihoodCoreNative
 * Method:    setUseScalingC
 * Signature: (JD)V
 */
JNIEXPORT void JNICALL Java_beast_evolution_likelihood_BeerLikelihoodCoreNative_setUseScalingC
  (JNIEnv *, jobject, jlong, jdouble);

/*
 * Class:     beast_evolution_likelihood_BeerLikelihoodCoreNative
 * Method:    calculatePartialsC
 * Signature: (JIII)V
 */
JNIEXPORT void JNICALL Java_beast_evolution_likelihood_BeerLikelihoodCoreNative_calculatePartialsC
  (JNIEnv *, jobject, jlong, jint, jint, jint);

/*
 * Class:     beast_evolution_likelihood_BeerLikelihoodCoreNative
 * Method:    integratePartialsC
 * Signature: (JI[D[D)V
 */
JNIEXPORT void JNICALL Java_beast_evolution_likelihood_BeerLikelihoodCoreNative_integratePartialsC
  (JNIEnv *, jobject, jlong, jint, jdoubleArray, jdoubleArray);

/*
 * Class:     beast_evolution_likelihood_BeerLikelihoodCoreNative
 * Method:    storeC
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_beast_evolution_likelihood_BeerLikelihoodCoreNative_storeC
  (JNIEnv *, jobject, jlong);

/*
 * Class:     beast_evolution_likelihood_BeerLikelihoodCoreNative
 * Method:    unstoreC
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_beast_evolution_likelihood_BeerLikelihoodCoreNative_unstoreC
  (JNIEnv *, jobject, jlong);

/*
 * Class:     beast_evolution_likelihood_BeerLikelihoodCoreNative
 * Method:    restoreC
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_beast_evolution_likelihood_BeerLikelihoodCoreNative_restoreC
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
