name: BEASTLabs tests
on: [ push, pull_request, workflow_dispatch ]

jobs:
  test-BEASTLabs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout BEASTLabs
        uses: actions/checkout@v2
        with:
          path: BEASTLabs

      - name: Set up JDK 8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8.0

      - name: Checkout beast2
        uses: actions/checkout@v2
        with:
          repository: CompEvol/beast2
          path: beast2

      - name: Find build.xml
        run: |
          pwd
          find . -name "build.xml"

      - name: Run BEASTlbs Ant
        run: ant -noinput -buildfile ./BEASTLabs/build.xml junitBEASTlabs
