name: BEASTLabs tests
on: [ push, pull_request, workflow_dispatch ]

jobs:
  test-BEASTLabs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout BEASTLabs
        uses: actions/checkout@v4
        with:
          path: BEASTLabs

      - name: Azul Zulu OpenJDK
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '25'
          java-package: jdk+fx

      - name: Checkout beast3
        uses: actions/checkout@v4
        with:
          repository: CompEvol/beast3
          path: beast3

      - name: Find build.xml
        run: |
          pwd
          find . -name "build.xml"

      - name: Build beast3
        run: ant -noinput -buildfile ./beast3/build.xml compile-all


      - name: Run BEASTlbs Ant
        run: ant -noinput -buildfile ./BEASTLabs/build.xml junitBEASTlabs

#      - name: Publish unit test results
#        uses: EnricoMi/publish-unit-test-result-action@v2
#        if: always()
#        with:
#          junit_files: BEASTLabs/build/junitreport/**/*.xml
