name: BEASTLabs tests
on: [ push, pull_request, workflow_dispatch ]

jobs:
  test-BEASTLabs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout BEASTLabs
        uses: actions/checkout@v3
        with:
          path: BEASTLabs

      - name: Azul Zulu OpenJDK
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'
          java-package: jdk+fx

      - name: Checkout beast2
        uses: actions/checkout@v3
        with:
          repository: CompEvol/beast2
          path: beast2

      - name: Checkout BeastFX
        uses: actions/checkout@v3
        with:
          repository: CompEvol/BeastFX
          path: BeastFX

      - name: Find build.xml
        run: |
          pwd
          find . -name "build.xml"

      - name: Build beast2
        run: ant -noinput -buildfile ./beast2/build.xml compile-all

      - name: Build BeastFX
        run: ant -noinput -buildfile ./BeastFX/build.xml compile-allBeastFX

      - name: Run BEASTlbs Ant
        run: ant -noinput -buildfile ./BEASTLabs/build.xml junitBEASTlabs

#      - name: Publish unit test results
#        uses: EnricoMi/publish-unit-test-result-action@v2
#        if: always()
#        with:
#          junit_files: BEASTLabs/build/junitreport/**/*.xml