name: BEASTLabs tests
on: [ push, pull_request, workflow_dispatch ]

jobs:
  test-BEASTLabs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout BEASTLabs
        uses: actions/checkout@v4
        with:
          path: BEASTLabs

      - name: Azul Zulu OpenJDK
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '25'
          java-package: jdk+fx
          cache: maven

      - name: Checkout beast3
        uses: actions/checkout@v4
        with:
          repository: CompEvol/beast3
          path: beast3

      - name: Install beagle.jar to local Maven repo
        run: >
          mvn install:install-file
          -Dfile=beast3/lib/beagle.jar
          -DgroupId=io.github.compevol
          -DartifactId=beagle
          -Dversion=1.0
          -Dpackaging=jar

      - name: Build and install beast3
        run: mvn -f beast3/pom.xml install -DskipTests -q

      - name: Build and test BEASTLabs
        run: mvn -f BEASTLabs/pom.xml test
